name: Maven Package

on:
  push:
    branches: ["main"]  # Triggers on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read  # Read access to the repository contents
      packages: write  # Write access to GitHub Packages

    steps:
      # Step 1: Checkout the repository's code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven  # Enable Maven caching for faster builds

      # Step 3: Build the Maven package
      - name: Build with Maven
        run: mvn -Dmaven.test.skip=true -B package --file pom.xml

